### ISSUE TITLE
工程的 docker 发布

### ISSUE THREAD

**Issue by ibuwei** [jeequan/jeepay#9]
## **这几天在尝试使用 docker 来部署整个项目, 下面是各文件具体内容:**

**1. docker-compose.yaml 文件的内容:**
```
cloud_eureka:
  build: ./xxpay4spring-cloud/xxpay-server/src/main/docker
  volumes:
      - "./data/log:/app/log"
  hostname: eureka
  ports:
    - "2000:2000"
  net: "host"

cloud_config:
  build: ./xxpay4spring-cloud/xxpay-config/src/main/docker
  volumes:
      - "./data/log:/app/log"
  hostname: config
  environment:
     EUREKA_HOST: eureka
     EUREKA_PORT: 2000
  ports:
      - "2020:2020"
  net: "host"

cloud_service:
  build: ./xxpay4spring-cloud/xxpay-service/src/main/docker
  volumes:
      - "./data/log:/app/log"
  hostname: service
  environment:
     EUREKA_HOST: eureka
     EUREKA_PORT: 2000
     SERVER_PORT: 3000
  ports:
    - "3000:3000"
  net: "host"

cloud_web:
  build: ./xxpay4spring-cloud/xxpay-web/src/main/docker
  volumes:
      - "./data/log:/app/log"
  hostname: web
  environment:
     EUREKA_HOST: eureka
     EUREKA_PORT: 2000
     SERVER_PORT: 3010
  ports:
    - "3010:3010"
  net: "host"

cloud_zuul:
  build: ./xxpay4spring-cloud/xxpay-gateway/src/main/docker
  volumes:
      - "./data/log:/app/log"
  hostname: zuul
  environment:
     EUREKA_HOST: eureka
     EUREKA_PORT: 2000
  ports:
    - "3021:3021"
  net: "host"

dubbo_service:
  build: ./xxpay4dubbo/xxpay4dubbo-service/src/main/docker
  volumes:
      - "./data/log:/app/log"
  hostname: dubbo_service
  environment:
     EUREKA_HOST: eureka
     EUREKA_PORT: 2000
  ports:
    - "20880:20880"
  net: "host"
dubbo_web:
  build: ./xxpay4dubbo/xxpay4dubbo-web/src/main/docker
  volumes:
      - "./data/log:/app/log"
  hostname: dubbo_web
  environment:
     EUREKA_HOST: eureka
     EUREKA_PORT: 2000
  ports:
    - "3020:3020"
  net: "host"
```

**2. 模块中的 Dockerfile 的样例:**
```
FROM registry.docker-cn.com/library/openjdk:8-jre-alpine
ADD alpine-repositories.list /etc/apk/repositories
RUN set -x && \
    apk add --update bash && \
    rm -rf /var/cache/apk/*
VOLUME /tmp
RUN mkdir /app
_#这里对应当前模块的 jar 文件名_
ADD xxpay-config.jar /app/app.jar
ADD runboot.sh /app/
RUN bash -c 'touch /app/app.jar'
WORKDIR /app
RUN chmod a+x runboot.sh
EXPOSE 2020
CMD /app/runboot.sh
```
**3. alpine-repositories.list 文件的内容:**
```
https://mirrors.ustc.edu.cn/alpine/latest-stable/main
https://mirrors.ustc.edu.cn/alpine/latest-stable/community
```
**4. runboot.sh 文件的内容:**
```
#!/usr/bin/env bash
_# 模块的启动间隔时间_
sleep 30
java -Djava.security.egd=file:/dev/./urandom -jar /app/app.jar
```
## **如果是在 linux 下, 可以使用以下的自动部署脚本:**
**1. 根目录下创建 docker-run.sh 脚本, 内容:**
```
#!/bin/sh
_# 一旦出现了返回值非零，整个脚本就会立即退出。_
set -e
_# 取得当前目录绝对路径_
basepath=$(cd `realpath .`; pwd)
_# 取得当前目录名称_
curfolder=${basepath##*/}

_# 创建需要的文件夹_
if [ ! -d ${basepath}/data ]; then
  mkdir -p ${basepath}/data/log
fi

_# 这里先使用 maven 构建项目_
docker build -t ncc-xxpay-img -f Dockerfile.build .
docker ps -a|grep ncc-mvn-builder|awk '{print $1}'|xargs -I {} docker rm "{}"
docker create --name ncc-mvn-builder ncc-xxpay-img
_# 循环复制 mvn 中的 jar 文件到 docker 文件夹路径下_
for file in $(find ./ -name Dockerfile -type f)
  do
  dockerfile_path=${file#./*}
  dockerfolder_path=${dockerfile_path%/*}
  project_path=${dockerfile_path%%/src*}
  project_name=${project_path##*/}
  docker cp ncc-mvn-builder:/usr/src/app/${project_path}/target/${project_name}.jar ${basepath}/${dockerfolder_path}/

  _# 顺便给 alpine 容器源替换成国内镜像_
  touch ${basepath}/${dockerfolder_path}/alpine-repositories.list
  echo "https://mirrors.ustc.edu.cn/alpine/latest-stable/main" >> ${basepath}/${dockerfolder_path}/alpine-repositories.list
  echo "https://mirrors.ustc.edu.cn/alpine/latest-stable/community" >> ${basepath}/${dockerfolder_path}/alpine-repositories.list
done;

_# 判断 docker-compose 是否存在_
if command -v docker-compose >/dev/null 2>&1; then
  echo 'exists docker-compose'
else
  _# 不存在则安装_
  curl -L https://get.daocloud.io/docker/compose/releases/download/1.3.1/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
  chmod +x /usr/local/bin/docker-compose
fi
_#先 build, 再启动_
docker-compose build
docker-compose up -d
```
**2. Dockerfile.build 的内容:**
```
FROM registry.cn-hangzhou.aliyuncs.com/narlian/maven:3-jdk-8-alpine
ENV MY_HOME=/usr/src/app
RUN mkdir -p $MY_HOME
WORKDIR $MY_HOME
ADD pom.xml $MY_HOME
_# get all the downloads out of the way_
RUN ["/usr/local/bin/mvn-entrypoint.sh","mvn","verify","clean","--fail-never"]
_# add source_
ADD . $MY_HOME
_# run maven verify_
RUN ["/usr/local/bin/mvn-entrypoint.sh","mvn","verify","-Dmaven.test.skip=true"]
CMD ["mvn","clean","package","-Dmaven.test.skip=true"]
```
